language: go

sudo: required
dist: trusty

env:
  - PGVERSION=9.3
  - PGVERSION=9.4
  - PGVERSION=9.5
  - PGVERSION=9.6

go:
  - 1.8.x
  - 1.9.x
  - master

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start $PGVERSION

before_script:
  - createdb -V
  - createdb pq_types

script: go test -v -check.v
